### ISSUE TITLE
Don't shim <- and {

### ISSUE THREAD

**Issue by krlmlr** [moodymudskipper/boomer#12] opened 2021-04-26 03:54 UTC
to avoid repetition of output.

``` r
library(boomer)
library(tidyverse)

test <- boomer::rigger() + function() {
  a <- 1 + 2 * 3
}

test()
#> 2 * 3
#> [1] 6
#> 1 + 2 * 3
#> [1] 7
#> a <- 1 + 2 * 3
#> [1] 7
#> {
#>     a <- 1 + 2 * 3
#> }
#> [1] 7
#> [1] 7
```

<sup>Created on 2021-04-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by moodymudskipper** [comment] 2021-04-26 08:03
It would make sense most of the time, but in some corner cases it would prevent {boomer}, from spotting that one of these is overridden.

I think we can have an additional argument `ignore` defaulting to a vector of those you suggest + other assignment ops and parenthesis.

The doc would mention that `::` and `:::` are never boomed.

**Comment by krlmlr** [comment] 2021-04-26 08:42
Added to PR.

**Comment by moodymudskipper** [comment] 2021-04-26 11:57
@krlmlr thanks, I've updated it to use options by default so the behavior of the addin can be easily modified too. And I've added `"="` to the list of ignored functions. 

https://github.com/moodymudskipper/boomer/commit/1a11a9145c6e2504c69050361b7e7de839beb502

**Comment by krlmlr** [comment] 2021-04-26 12:53
The `"="` gives weird behavior on my end, I use `ignore = c("~", "{", "(", "<-", "<<-")` for now.

**Comment by moodymudskipper** [comment] 2021-04-26 13:31
Do you have something reproducible ?

**Comment by krlmlr** [comment] 2021-04-26 13:38
Not yet. The error message mentioned `names<-` and `.Primitive("<-")`, I was happy to find the workaround :sweat_smile:

**Comment by moodymudskipper** [comment] 2021-06-10 23:11
Since we've had quite a few changes since then and don't have anything reproducible, I'm closing for now

**Closed by moodymudskipper** 2021-06-10 23:11 UTC

**Comment by krlmlr** [comment] 2021-06-11 00:51
Today:

``` r
library(boomer)
library(tidyverse)

test <- boomer::rigger() + function() {
  a <- 1 + 2 * 3
}

test()
#> 👇 e2
#> 💣 +
#> · 💣 *
#> · 💥 2 * 3
#> · [1] 6
#> · 
#> 💥 1 + 2 * 3
#> [1] 7
#> 
#> 👆 e2
```

<sup>Created on 2021-06-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

I think it's fine, thanks for looking into it!
